matrix:
  DEFAULT_ENVIRONMENT:
    - cdp-dev
    # - cdp-sys
  SLACK_NOTICE_CHANNEL_SUCCESS:
    - cdp-deploy-success
  SLACK_NOTICE_CHANNEL_FAILURE:
    - cdp-deploy-failure
  SLACK_NOTICE_ICON:
    - https://avatars.slack-edge.com/2019-03-25/588775175286_f3831480e0ca04ab5358_48.png
  SLACK_NOTICE_USERNAME:
    - Drone
  DOCKER_CDP_CI_IMAGE:
    - 0.4.2

pipeline:
  deploy-to-cdp-dev:
    image: quay.io/ukhomeofficedigital/cdp-ci:${DOCKER_CDP_CI_IMAGE}
    secrets:
      - kube_token
      - kube_server
      # - github_ssh_key_cdp_deploy
    commands:
      # DRONE_DEPLOY_TO is set by the drone-trigger plugin
      - deploy.sh . ${DRONE_DEPLOY_TO}
    when:
      event: deployment
      branch: master

  deploy:
    image: quay.io/ukhomeofficedigital/cdp-ci:${DOCKER_CDP_CI_IMAGE}
    secrets:
      - kube_token
      - kube_server
      # - github_ssh_key_cdp_deploy
    environment:
      - KUBE_FOO=foo
    commands:
      - echo 1 KUBE_FOO=$${KUBE_FOO}
      - echo 2 KUBE_FOO=${KUBE_FOO}
      - echo 3 KUBE_SERVER=$${KUBE_SERVER}
      - kubectl get pods --server=$${KUBE_SERVER} --token=$${KUBE_TOKEN} --namespace=${DEFAULT_ENVIRONMENT} --insecure-skip-tls-verify
      - deploy.sh . ${DEFAULT_ENVIRONMENT}
    when:
      # repo:
      #   - github.com/UKHomeOffice/cdp-deployment-templates
      event: push
      branch: [master, CDMP-2264]

  # notify_slack_success_push:
  #   image: plugins/slack:1.2
  #   secrets:
  #     - source: "slack_webhook_cdp_deploy_success"
  #       target: slack_webhook
  #   channel: ${SLACK_NOTICE_CHANNEL_SUCCESS}
  #   username: ${SLACK_NOTICE_USERNAME}
  #   icon_url: ${SLACK_NOTICE_ICON}
  #   template: >
  #     *Deployed to ${DEFAULT_ENVIRONMENT} * - <{{build.link}}|#{{build.number}}>
  #   when:
  #     branch: [master]
  #     event: push
  #     status: success

  # notify_slack_failure_push:
  #   image: plugins/slack:1.2
  #   secrets:
  #     - source: "slack_webhook_cdp_deploy_failure"
  #       target: slack_webhook
  #   channel: ${SLACK_NOTICE_CHANNEL_FAILURE}
  #   username: ${SLACK_NOTICE_USERNAME}
  #   icon_url: ${SLACK_NOTICE_ICON}
  #   template: >
  #     *Failed to deploy to ${DEFAULT_ENVIRONMENT}*

  #     Author: {{build.author}}

  #     Duration: {{since job.started}}
  #     Job: <{{build.link}}|#{{build.number}}>

  #     Commit: {{build.commit}}
  #   when:
  #     branch: [master]
  #     event: push
  #     status: failure
